import type { MatchingProfile, MatchingFilter } from './types'

export const mockFilters: MatchingFilter[] = [
  { id: 'city', label: 'Москва' },
  { id: 'sport', label: 'Спорт' },
  { id: 'music', label: 'Музыка' },
  { id: 'photo', label: 'Фото' },
  { id: 'travel', label: 'Путешествия' },
  { id: 'games', label: 'Игры' },
  { id: 'books', label: 'Книги' },
  { id: 'movies', label: 'Кино' },
]

export const mockProfiles: MatchingProfile[] = [
  {
    id: 1,
    firstName: 'Анна',
    lastName: 'К.',
    age: 24,
    city: 'Москва',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&h=800&fit=crop',
    about: 'Люблю активный отдых, спорт и путешествия. Ищу компанию для пробежек по утрам и походов в горы. Ценю искренность и чувство юмора.',
    jobTitle: 'UX-дизайнер',
    department: 'Продуктовый отдел',
    workFormat: 'REMOTE',
    goal: 'NEW_FRIENDS',
    personalityType: 'EXTROVERT',
    communicationFormat: ['ONLINE', 'OFFLINE'],
    interests: [
      { name: 'Бег', level: 5 },
      { name: 'Йога', level: 4 },
      { name: 'Фотография', level: 3 },
      { name: 'Путешествия', level: 5 },
      { name: 'Кулинария', level: 3 },
    ],
    photos: [
      'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&h=800&fit=crop',
    ],
  },
  {
    id: 2,
    firstName: 'Мария',
    lastName: 'С.',
    age: 26,
    city: 'Санкт-Петербург',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&h=800&fit=crop',
    about: 'Software engineer, увлекаюсь современным искусством и книгами. По вечерам играю на гитаре. Ищу интересного собеседника для прогулок по городу.',
    jobTitle: 'Senior Developer',
    department: 'Engineering',
    workFormat: 'HYBRID',
    goal: 'RELATIONSHIP',
    personalityType: 'AMBIVERT',
    communicationFormat: ['ONLINE', 'OFFLINE'],
    interests: [
      { name: 'Программирование', level: 5 },
      { name: 'Музыка', level: 4 },
      { name: 'Книги', level: 5 },
      { name: 'Искусство', level: 3 },
    ],
    photos: [
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=600&h=800&fit=crop',
    ],
  },
  {
    id: 3,
    firstName: 'Екатерина',
    lastName: 'В.',
    age: 28,
    city: 'Москва',
    avatarUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&h=800&fit=crop',
    about: 'Маркетолог с любовью к танцам и кофе. Открыта новым знакомствам и интересным проектам. В свободное время занимаюсь волонтёрством.',
    jobTitle: 'Маркетолог',
    department: 'Маркетинг',
    workFormat: 'OFFICE',
    goal: 'NETWORKING',
    personalityType: 'EXTROVERT',
    communicationFormat: ['OFFLINE'],
    interests: [
      { name: 'Танцы', level: 5 },
      { name: 'Маркетинг', level: 4 },
      { name: 'Кофе', level: 4 },
      { name: 'Волонтёрство', level: 3 },
      { name: 'Дизайн', level: 3 },
    ],
    photos: [
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&h=800&fit=crop',
    ],
  },
  {
    id: 4,
    firstName: 'Дарья',
    lastName: 'М.',
    age: 23,
    city: 'Казань',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=600&h=800&fit=crop',
    about: 'Студентка, изучаю архитектуру. Люблю фотографировать здания и гулять по историческим местам. Веган, увлекаюсь здоровым питанием.',
    jobTitle: 'Студент',
    department: 'Архитектура',
    workFormat: 'OFFICE',
    goal: 'NEW_FRIENDS',
    personalityType: 'INTROVERT',
    communicationFormat: ['ONLINE', 'OFFLINE'],
    interests: [
      { name: 'Архитектура', level: 5 },
      { name: 'Фотография', level: 4 },
      { name: 'Здоровое питание', level: 4 },
      { name: 'История', level: 3 },
    ],
    photos: [
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1554151228-14d9def656e4?w=600&h=800&fit=crop',
    ],
  },
]
